-- local function git_branch()
--   local handle = io.popen("git branch --show-current 2>/dev/null")
--   local branch = handle:read("*a"):gsub("\n", "")
--   handle:close()
--   return branch ~= "" and ("  " .. branch .. " ") or ""
-- end
-- 
-- vim.o.statusline = "%f %h%m%r" ..
--                    "%=" ..
--                    git_branch()
