# vim-like keybindings
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Shift + Alt + H/L for previous/next window
bind -n M-H previous-window
bind -n M-L next-window

# sane settings
set -g base-index 1
setw -g pane-base-index 1
set -s escape-time 0
set -g mouse on
set -g renumber-windows
set -g history-limit 20000
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Open panes in current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind '%' split-window -h -c "#{pane_curent_path}"

# fix colors
set  -g default-terminal "tmux-256color"
set -ag terminal-overrides ",alacritty:RGB"

# status bar
set -g status-justify left
set -g status-right "#(cd #{pane_current_path}; git rev-parse --abbrev-ref HEAD) %H:%M"
set-option -g status-position top
set-option -g status-left-length 200
set-option -g window-status-separator ""
set-option -g status-bg "#1d2031"
set-option -g status-left "#[bg=#8aadf5,fg=#1d2031]  #{session_name} "
set-option -g window-status-format "#[bg=#1d2031,fg=#cad3f6] #I:#W#F "
set-option -g window-status-current-format "#[bg=#25273a,fg=#cad3f6] #I:#W#F "

# tpm and plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'fcsonline/tmux-thumbs'
set -g @plugin 'tmux-plugins/tmux-yank'

run-shell ~/.tmux/plugins/tmux-thumbs/tmux-thumbs.tmux
run '~/.tmux/plugins/tpm/tpm'
